Add DynamicHMap Improvements
Geopipe/Cxx-Heterogeneous-Maps pull request #4
Opened 2020-11-23 19:28 UTC by johnrgrout

This pull request adds fixes to the ptrCopyOut and ptrCopyOutOne functions so they won't throw an any_cast exception and a print function to help with debugging.

2020-12-20 18:25 UTC, KermMartian commented
@elfprince13 please review/approve at your convenience; this seems more in your wheelhouse.

2020-12-21 18:51 UTC, elfprince13 requested changes

2020-12-21 18:51 UTC, elfprince13 commented on src/dynamic-hmap.cc
> +}
A good printing function seems like it should go in a different PR, and have slightly more features rather than baking it into the API here.

2021-09-23 15:39 UTC, elfprince13 approved these changes

2021-09-23 15:40 UTC, merged